---
- name: Deploy Docker Compose
  hosts: localhost

  tasks:
    - name: Copy .env file for java application
      copy:
        src: ./.env
        dest: /home/devops/garage-project/.env

    - name: Export env variables
      shell: "/bin/sh -c 'set -a && . /home/devops/garage-project/.env && set +a'"

    - name: Debug export
      shell: "/bin/sh -c 'env'"

    - name: Copy jar file
      copy:
        src: ./target/gp-0.0.1-SNAPSHOT.jar
        dest: /home/devops/garage-project/gp-0.0.1-SNAPSHOT.jar

    - name: Copy Docker Compose Services file
      copy:
        src: ./docker-compose-services.yaml
        dest: /home/devops/garage-project/docker-compose-services.yaml

    - name: Start Docker Services
      command: docker compose -f /home/devops/garage-project/docker-compose-services.yaml up -d

    - name: Start java application
      command: nohup java -jar /home/devops/garage-project/gp-0.0.1-SNAPSHOT.jar &