---
- name: Deploy Docker Compose
  hosts: localhost

  tasks:
    - name: Copy .env file for java application
      copy:
        src: ./.env
        dest: /home/devops/garage-project/.env

    - name: Copy jar file
      copy:
        src: ./target/gp-0.0.1-SNAPSHOT.jar
        dest: /home/devops/garage-project/gp-0.0.1-SNAPSHOT.jar

    - name: Start java application
      command: java -jar /home/devops/garage-project/gp-0.0.1-SNAPSHOT.jar

    - name: Copy Docker Compose file
      copy:
        src: ./docker-compose.yaml
        dest: /home/devops/garage-project/docker-compose.yaml

    - name: Start Docker Compose services
      command: docker compose -f /home/devops/garage-project/docker-compose.yaml up -d
