---
- name: Deploy Services in Docker and Jar
  hosts: localhost

  tasks:
    - name: Copy .env file for java application
      copy:
        src: ./.env
        dest: /home/devops/docker-services/.env

    - name: Copy Docker Compose Services file
      copy:
        src: ./docker-compose-services.yaml
        dest: /home/devops/docker-services/docker-compose-services.yaml

    - name: Start Docker Services
      command: docker compose -f /home/devops/docker-services/docker-compose-services.yaml up -d

    - name: Copy jar file
      copy:
        src: ./target/gp-0.0.1-SNAPSHOT.jar
        dest: /home/devops/garage-project/gp-0.0.1-SNAPSHOT.jar

    - name: Start java application
      shell: "/bin/bash -c 'nohup java -jar /home/devops/garage-project/gp-0.0.1-SNAPSHOT.jar --spring.profiles.active=local >> /home/devops/garage-project/logs.txt 2>&1 &'"