---
- name: Deploy Services in Docker and Jar
  hosts: localhost

  tasks:
    - name: Copy .env file for java application
      copy:
        src: ./.env
        dest: /home/devops/garage-project-docker/.env

    - name: Copy Docker Compose Services file
      copy:
        src: ./docker-compose-services.yaml
        dest: /home/devops/garage-project-docker/docker-compose-services.yaml

    - name: Start Docker Services
      command: docker compose -f /home/devops/garage-project-docker/docker-compose-services.yaml up -d

    - name: Wait until HTTP status is 200
      uri:
        url: 'https://devops-assignment.francecentral.cloudapp.azure.com/auth/'
        return_content: yes
        validate_certs: no
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 24 # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
      delay: 5 # Every 5 seconds
      register: result

    - name: Copy jar file
      copy:
        src: ./target/gp-0.0.1-SNAPSHOT.jar
        dest: /home/devops/garage-project/gp-0.0.1-SNAPSHOT.jar

    - name: Start java application
      shell: "/bin/bash -c 'nohup java -jar /home/devops/garage-project/gp-0.0.1-SNAPSHOT.jar --spring.profiles.active=local >> /home/devops/garage-project/logs.txt 2>&1 &'"